backend:
  name: git-gateway
  branch: main # Replace with your branch name if not 'main'

media_folder: "images/uploads" # Folder for uploaded images
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages" # Replace with your content folder
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
